# Generated by Django 3.0.6 on 2020-05-06 09:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='Ratings',
        ),
    ]
